name: Build, push and deploy staking dashboard to mainnet

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-20.04
    environment: 
      name: mainnet
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v3

      - name: DOCKER | Build and push mainnet image
        uses: ./.github/actions/build-and-push
        id: build_mainnet
        with:
          environment: mainnet
          build_envs: "REACT_APP_DISABLE_FIAT=1"
          aws_mainnet_access_key_id: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          aws_mainnet_secret_access_key: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
    outputs:
      image_tag: ${{ steps.build_mainnet.outputs.image_tag }}
  
  deploy_to_mainnet:
    name: Deploy to mainnet
    runs-on: ubuntu-20.04
    needs: [build_and_push]
    environment: 
      name: mainnet
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v3

      - name: MAINNET | Deploy staking dashboard
        uses: ./.github/actions/deploy
        id: deploy_mainnet
        with:
          environment: mainnet
          image_tag: ${{ needs.build_and_push.outputs.image_tag }}
          github_token: ${{ secrets.CI_GH_TOKEN }}
